const TEST_EXTERNAL_ID = -100;

const LABELED = {
  action: 'labeled',
  issue: {
    active_lock_reason: null,
    assignee: null,
    assignees: [],
    author_association: 'CONTRIBUTOR',
    body: 'sad',
    closed_at: null,
    comments: 0,
    comments_url: 'https://api.github.com/repos/test/test/issues/52/comments',
    created_at: '2022-08-25T16:43:39Z',
    events_url: 'https://api.github.com/repos/test/test/issues/52/events',
    html_url: 'https://github.com/test/test/issues/52',
    id: 1351182500,
    labels: [
      {
        color: '6E9669',
        default: false,
        description: '',
        id: 4429203554,
        name: 'te',
        node_id: 'LA_kwDOHycosM8AAAABCABIYg',
        url: 'https://api.github.com/repos/test/test/labels/te',
      },
    ],
    labels_url:
      'https://api.github.com/repos/test/test/issues/52/labels{/name}',
    locked: false,
    milestone: null,
    node_id: 'I_kwDOHycosM5QiWik',
    number: TEST_EXTERNAL_ID,
    performed_via_github_app: null,
    reactions: {
      '+1': 0,
      '-1': 0,
      confused: 0,
      eyes: 0,
      heart: 0,
      hooray: 0,
      laugh: 0,
      rocket: 0,
      total_count: 0,
      url: 'https://api.github.com/repos/test/test/issues/52/reactions',
    },
    repository_url: 'https://api.github.com/repos/test/test',
    state: 'open',
    state_reason: null,
    timeline_url: 'https://api.github.com/repos/test/test/issues/52/timeline',
    title: 'asdf',
    updated_at: '2022-08-25T16:44:16Z',
    url: 'https://api.github.com/repos/test/test/issues/52',
    user: {
      avatar_url: 'https://avatars.githubusercontent.com/u/1747664?v=4',
      events_url: 'https://api.github.com/users/BuffaloDrew/events{/privacy}',
      followers_url: 'https://api.github.com/users/BuffaloDrew/followers',
      following_url:
        'https://api.github.com/users/BuffaloDrew/following{/other_user}',
      gists_url: 'https://api.github.com/users/BuffaloDrew/gists{/gist_id}',
      gravatar_id: '',
      html_url: 'https://github.com/BuffaloDrew',
      id: 1747664,
      login: 'BuffaloDrew',
      node_id: 'MDQ6VXNlcjE3NDc2NjQ=',
      organizations_url: 'https://api.github.com/users/BuffaloDrew/orgs',
      received_events_url:
        'https://api.github.com/users/BuffaloDrew/received_events',
      repos_url: 'https://api.github.com/users/BuffaloDrew/repos',
      site_admin: false,
      starred_url:
        'https://api.github.com/users/BuffaloDrew/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/BuffaloDrew/subscriptions',
      type: 'User',
      url: 'https://api.github.com/users/BuffaloDrew',
    },
  },
  label: {
    color: '6E9669',
    default: false,
    description: '',
    id: 4429203554,
    name: 'test label',
    node_id: 'LA_kwDOHycosM8AAAABCABIYg',
    url: 'https://api.github.com/repos/test/test/labels/te',
  },
  organization: {
    avatar_url: 'https://avatars.githubusercontent.com/u/110850163?v=4',
    description: null,
    events_url: 'https://api.github.com/orgs/ui-te-test/events',
    hooks_url: 'https://api.github.com/orgs/ui-te-test/hooks',
    id: 110850163,
    issues_url: 'https://api.github.com/orgs/ui-te-test/issues',
    login: 'ui-te-test',
    members_url: 'https://api.github.com/orgs/ui-te-test/members{/member}',
    node_id: 'O_kgDOBptwcw',
    public_members_url:
      'https://api.github.com/orgs/ui-te-test/public_members{/member}',
    repos_url: 'https://api.github.com/orgs/ui-te-test/repos',
    url: 'https://api.github.com/orgs/ui-te-test',
  },
  repository: {
    allow_forking: false,
    archive_url:
      'https://api.github.com/repos/test/test/{archive_format}{/ref}',
    archived: false,
    assignees_url: 'https://api.github.com/repos/test/test/assignees{/user}',
    blobs_url: 'https://api.github.com/repos/test/test/git/blobs{/sha}',
    branches_url: 'https://api.github.com/repos/test/test/branches{/branch}',
    clone_url: 'https://github.com/test/test.git',
    collaborators_url:
      'https://api.github.com/repos/test/test/collaborators{/collaborator}',
    comments_url: 'https://api.github.com/repos/test/test/comments{/number}',
    commits_url: 'https://api.github.com/repos/test/test/commits{/sha}',
    compare_url:
      'https://api.github.com/repos/test/test/compare/{base}...{head}',
    contents_url: 'https://api.github.com/repos/test/test/contents/{+path}',
    contributors_url: 'https://api.github.com/repos/test/test/contributors',
    created_at: '2022-08-08T18:17:16Z',
    default_branch: 'main',
    deployments_url: 'https://api.github.com/repos/test/test/deployments',
    description: null,
    disabled: false,
    downloads_url: 'https://api.github.com/repos/test/test/downloads',
    events_url: 'https://api.github.com/repos/test/test/events',
    fork: false,
    forks: 0,
    forks_count: 0,
    forks_url: 'https://api.github.com/repos/test/test/forks',
    full_name: 'test/test',
    git_commits_url: 'https://api.github.com/repos/test/test/git/commits{/sha}',
    git_refs_url: 'https://api.github.com/repos/test/test/git/refs{/sha}',
    git_tags_url: 'https://api.github.com/repos/test/test/git/tags{/sha}',
    git_url: 'git://github.com/test/test.git',
    has_downloads: true,
    has_issues: true,
    has_pages: false,
    has_projects: true,
    has_wiki: true,
    homepage: null,
    hooks_url: 'https://api.github.com/repos/test/test/hooks',
    html_url: 'https://github.com/test/test',
    id: 522660016,
    is_template: false,
    issue_comment_url:
      'https://api.github.com/repos/test/test/issues/comments{/number}',
    issue_events_url:
      'https://api.github.com/repos/test/test/issues/events{/number}',
    issues_url: 'https://api.github.com/repos/test/test/issues{/number}',
    keys_url: 'https://api.github.com/repos/test/test/keys{/key_id}',
    labels_url: 'https://api.github.com/repos/test/test/labels{/name}',
    language: null,
    languages_url: 'https://api.github.com/repos/test/test/languages',
    license: null,
    merges_url: 'https://api.github.com/repos/test/test/merges',
    milestones_url:
      'https://api.github.com/repos/test/test/milestones{/number}',
    mirror_url: null,
    name: 'test',
    node_id: 'R_kgDOHycosA',
    notifications_url:
      'https://api.github.com/repos/test/test/notifications{?since,all,participating}',
    open_issues: 30,
    open_issues_count: 30,
    owner: {
      avatar_url: 'https://avatars.githubusercontent.com/u/110850163?v=4',
      events_url: 'https://api.github.com/users/ui-te-test/events{/privacy}',
      followers_url: 'https://api.github.com/users/ui-te-test/followers',
      following_url:
        'https://api.github.com/users/ui-te-test/following{/other_user}',
      gists_url: 'https://api.github.com/users/ui-te-test/gists{/gist_id}',
      gravatar_id: '',
      html_url: 'https://github.com/ui-te-test',
      id: 110850163,
      login: 'ui-te-test',
      node_id: 'O_kgDOBptwcw',
      organizations_url: 'https://api.github.com/users/ui-te-test/orgs',
      received_events_url:
        'https://api.github.com/users/ui-te-test/received_events',
      repos_url: 'https://api.github.com/users/ui-te-test/repos',
      site_admin: false,
      starred_url:
        'https://api.github.com/users/ui-te-test/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/ui-te-test/subscriptions',
      type: 'Organization',
      url: 'https://api.github.com/users/ui-te-test',
    },
    private: true,
    pulls_url: 'https://api.github.com/repos/test/test/pulls{/number}',
    pushed_at: '2022-08-25T14:24:16Z',
    releases_url: 'https://api.github.com/repos/test/test/releases{/id}',
    size: 157,
    ssh_url: 'git@github.com:test/test.git',
    stargazers_count: 0,
    stargazers_url: 'https://api.github.com/repos/test/test/stargazers',
    statuses_url: 'https://api.github.com/repos/test/test/statuses/{sha}',
    subscribers_url: 'https://api.github.com/repos/test/test/subscribers',
    subscription_url: 'https://api.github.com/repos/test/test/subscription',
    svn_url: 'https://github.com/test/test',
    tags_url: 'https://api.github.com/repos/test/test/tags',
    teams_url: 'https://api.github.com/repos/test/test/teams',
    topics: [],
    trees_url: 'https://api.github.com/repos/test/test/git/trees{/sha}',
    updated_at: '2022-08-25T14:23:06Z',
    url: 'https://api.github.com/repos/test/test',
    visibility: 'private',
    watchers: 0,
    watchers_count: 0,
    web_commit_signoff_required: false,
  },
  sender: {
    avatar_url: 'https://avatars.githubusercontent.com/u/1747664?v=4',
    events_url: 'https://api.github.com/users/BuffaloDrew/events{/privacy}',
    followers_url: 'https://api.github.com/users/BuffaloDrew/followers',
    following_url:
      'https://api.github.com/users/BuffaloDrew/following{/other_user}',
    gists_url: 'https://api.github.com/users/BuffaloDrew/gists{/gist_id}',
    gravatar_id: '',
    html_url: 'https://github.com/BuffaloDrew',
    id: 1747664,
    login: 'BuffaloDrew',
    node_id: 'MDQ6VXNlcjE3NDc2NjQ=',
    organizations_url: 'https://api.github.com/users/BuffaloDrew/orgs',
    received_events_url:
      'https://api.github.com/users/BuffaloDrew/received_events',
    repos_url: 'https://api.github.com/users/BuffaloDrew/repos',
    site_admin: false,
    starred_url:
      'https://api.github.com/users/BuffaloDrew/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/BuffaloDrew/subscriptions',
    type: 'User',
    url: 'https://api.github.com/users/BuffaloDrew',
  },
};

const OPENED = {
  action: 'opened',
  issue: {
    active_lock_reason: null,
    assignee: null,
    assignees: [],
    author_association: 'CONTRIBUTOR',
    body: 'Here is my description',
    closed_at: null,
    comments: 0,
    comments_url: 'https://api.github.com/repos/test/test/issues/54/comments',
    created_at: '2022-08-25T17:21:26Z',
    events_url: 'https://api.github.com/repos/test/test/issues/54/events',
    html_url: 'https://github.com/test/test/issues/54',
    id: 1351220757,
    labels: [],
    labels_url:
      'https://api.github.com/repos/test/test/issues/54/labels{/name}',
    locked: false,
    milestone: null,
    node_id: 'I_kwDOHycosM5Qif4V',
    number: TEST_EXTERNAL_ID,
    performed_via_github_app: null,
    reactions: {
      '+1': 0,
      '-1': 0,
      confused: 0,
      eyes: 0,
      heart: 0,
      hooray: 0,
      laugh: 0,
      rocket: 0,
      total_count: 0,
      url: 'https://api.github.com/repos/test/test/issues/54/reactions',
    },
    repository_url: 'https://api.github.com/repos/test/test',
    state: 'open',
    state_reason: null,
    timeline_url: 'https://api.github.com/repos/test/test/issues/54/timeline',
    title: 'New Issue Created',
    updated_at: '2022-08-25T17:21:26Z',
    url: 'https://api.github.com/repos/test/test/issues/54',
    user: {
      avatar_url: 'https://avatars.githubusercontent.com/u/1747664?v=4',
      events_url: 'https://api.github.com/users/BuffaloDrew/events{/privacy}',
      followers_url: 'https://api.github.com/users/BuffaloDrew/followers',
      following_url:
        'https://api.github.com/users/BuffaloDrew/following{/other_user}',
      gists_url: 'https://api.github.com/users/BuffaloDrew/gists{/gist_id}',
      gravatar_id: '',
      html_url: 'https://github.com/BuffaloDrew',
      id: 1747664,
      login: 'BuffaloDrew',
      node_id: 'MDQ6VXNlcjE3NDc2NjQ=',
      organizations_url: 'https://api.github.com/users/BuffaloDrew/orgs',
      received_events_url:
        'https://api.github.com/users/BuffaloDrew/received_events',
      repos_url: 'https://api.github.com/users/BuffaloDrew/repos',
      site_admin: false,
      starred_url:
        'https://api.github.com/users/BuffaloDrew/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/BuffaloDrew/subscriptions',
      type: 'User',
      url: 'https://api.github.com/users/BuffaloDrew',
    },
  },
  organization: {
    avatar_url: 'https://avatars.githubusercontent.com/u/110850163?v=4',
    description: null,
    events_url: 'https://api.github.com/orgs/ui-te-test/events',
    hooks_url: 'https://api.github.com/orgs/ui-te-test/hooks',
    id: 110850163,
    issues_url: 'https://api.github.com/orgs/ui-te-test/issues',
    login: 'ui-te-test',
    members_url: 'https://api.github.com/orgs/ui-te-test/members{/member}',
    node_id: 'O_kgDOBptwcw',
    public_members_url:
      'https://api.github.com/orgs/ui-te-test/public_members{/member}',
    repos_url: 'https://api.github.com/orgs/ui-te-test/repos',
    url: 'https://api.github.com/orgs/ui-te-test',
  },
  repository: {
    allow_forking: false,
    archive_url:
      'https://api.github.com/repos/test/test/{archive_format}{/ref}',
    archived: false,
    assignees_url: 'https://api.github.com/repos/test/test/assignees{/user}',
    blobs_url: 'https://api.github.com/repos/test/test/git/blobs{/sha}',
    branches_url: 'https://api.github.com/repos/test/test/branches{/branch}',
    clone_url: 'https://github.com/test/test.git',
    collaborators_url:
      'https://api.github.com/repos/test/test/collaborators{/collaborator}',
    comments_url: 'https://api.github.com/repos/test/test/comments{/number}',
    commits_url: 'https://api.github.com/repos/test/test/commits{/sha}',
    compare_url:
      'https://api.github.com/repos/test/test/compare/{base}...{head}',
    contents_url: 'https://api.github.com/repos/test/test/contents/{+path}',
    contributors_url: 'https://api.github.com/repos/test/test/contributors',
    created_at: '2022-08-08T18:17:16Z',
    default_branch: 'main',
    deployments_url: 'https://api.github.com/repos/test/test/deployments',
    description: null,
    disabled: false,
    downloads_url: 'https://api.github.com/repos/test/test/downloads',
    events_url: 'https://api.github.com/repos/test/test/events',
    fork: false,
    forks: 0,
    forks_count: 0,
    forks_url: 'https://api.github.com/repos/test/test/forks',
    full_name: 'test/test',
    git_commits_url: 'https://api.github.com/repos/test/test/git/commits{/sha}',
    git_refs_url: 'https://api.github.com/repos/test/test/git/refs{/sha}',
    git_tags_url: 'https://api.github.com/repos/test/test/git/tags{/sha}',
    git_url: 'git://github.com/test/test.git',
    has_downloads: true,
    has_issues: true,
    has_pages: false,
    has_projects: true,
    has_wiki: true,
    homepage: null,
    hooks_url: 'https://api.github.com/repos/test/test/hooks',
    html_url: 'https://github.com/test/test',
    id: 522660016,
    is_template: false,
    issue_comment_url:
      'https://api.github.com/repos/test/test/issues/comments{/number}',
    issue_events_url:
      'https://api.github.com/repos/test/test/issues/events{/number}',
    issues_url: 'https://api.github.com/repos/test/test/issues{/number}',
    keys_url: 'https://api.github.com/repos/test/test/keys{/key_id}',
    labels_url: 'https://api.github.com/repos/test/test/labels{/name}',
    language: null,
    languages_url: 'https://api.github.com/repos/test/test/languages',
    license: null,
    merges_url: 'https://api.github.com/repos/test/test/merges',
    milestones_url:
      'https://api.github.com/repos/test/test/milestones{/number}',
    mirror_url: null,
    name: 'test',
    node_id: 'R_kgDOHycosA',
    notifications_url:
      'https://api.github.com/repos/test/test/notifications{?since,all,participating}',
    open_issues: 32,
    open_issues_count: 32,
    owner: {
      avatar_url: 'https://avatars.githubusercontent.com/u/110850163?v=4',
      events_url: 'https://api.github.com/users/ui-te-test/events{/privacy}',
      followers_url: 'https://api.github.com/users/ui-te-test/followers',
      following_url:
        'https://api.github.com/users/ui-te-test/following{/other_user}',
      gists_url: 'https://api.github.com/users/ui-te-test/gists{/gist_id}',
      gravatar_id: '',
      html_url: 'https://github.com/ui-te-test',
      id: 110850163,
      login: 'ui-te-test',
      node_id: 'O_kgDOBptwcw',
      organizations_url: 'https://api.github.com/users/ui-te-test/orgs',
      received_events_url:
        'https://api.github.com/users/ui-te-test/received_events',
      repos_url: 'https://api.github.com/users/ui-te-test/repos',
      site_admin: false,
      starred_url:
        'https://api.github.com/users/ui-te-test/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/ui-te-test/subscriptions',
      type: 'Organization',
      url: 'https://api.github.com/users/ui-te-test',
    },
    private: true,
    pulls_url: 'https://api.github.com/repos/test/test/pulls{/number}',
    pushed_at: '2022-08-25T14:24:16Z',
    releases_url: 'https://api.github.com/repos/test/test/releases{/id}',
    size: 157,
    ssh_url: 'git@github.com:test/test.git',
    stargazers_count: 0,
    stargazers_url: 'https://api.github.com/repos/test/test/stargazers',
    statuses_url: 'https://api.github.com/repos/test/test/statuses/{sha}',
    subscribers_url: 'https://api.github.com/repos/test/test/subscribers',
    subscription_url: 'https://api.github.com/repos/test/test/subscription',
    svn_url: 'https://github.com/test/test',
    tags_url: 'https://api.github.com/repos/test/test/tags',
    teams_url: 'https://api.github.com/repos/test/test/teams',
    topics: [],
    trees_url: 'https://api.github.com/repos/test/test/git/trees{/sha}',
    updated_at: '2022-08-25T14:23:06Z',
    url: 'https://api.github.com/repos/test/test',
    visibility: 'private',
    watchers: 0,
    watchers_count: 0,
    web_commit_signoff_required: false,
  },
  sender: {
    avatar_url: 'https://avatars.githubusercontent.com/u/1747664?v=4',
    events_url: 'https://api.github.com/users/BuffaloDrew/events{/privacy}',
    followers_url: 'https://api.github.com/users/BuffaloDrew/followers',
    following_url:
      'https://api.github.com/users/BuffaloDrew/following{/other_user}',
    gists_url: 'https://api.github.com/users/BuffaloDrew/gists{/gist_id}',
    gravatar_id: '',
    html_url: 'https://github.com/BuffaloDrew',
    id: 1747664,
    login: 'BuffaloDrew',
    node_id: 'MDQ6VXNlcjE3NDc2NjQ=',
    organizations_url: 'https://api.github.com/users/BuffaloDrew/orgs',
    received_events_url:
      'https://api.github.com/users/BuffaloDrew/received_events',
    repos_url: 'https://api.github.com/users/BuffaloDrew/repos',
    site_admin: false,
    starred_url:
      'https://api.github.com/users/BuffaloDrew/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/BuffaloDrew/subscriptions',
    type: 'User',
    url: 'https://api.github.com/users/BuffaloDrew',
  },
};

const COMMENT_CREATED = {
  action: 'created',
  comment: {
    author_association: 'CONTRIBUTOR',
    body: 'Test Comment',
    created_at: '2022-08-25T17:33:36Z',
    html_url: 'https://github.com/test/test/issues/54#issuecomment-1227570618',
    id: 1227570618,
    issue_url: 'https://api.github.com/repos/test/test/issues/54',
    node_id: 'IC_kwDOHycosM5JKz26',
    performed_via_github_app: null,
    reactions: {
      '+1': 0,
      '-1': 0,
      confused: 0,
      eyes: 0,
      heart: 0,
      hooray: 0,
      laugh: 0,
      rocket: 0,
      total_count: 0,
      url: 'https://api.github.com/repos/test/test/issues/comments/1227570618/reactions',
    },
    updated_at: '2022-08-25T17:33:36Z',
    url: 'https://api.github.com/repos/test/test/issues/comments/1227570618',
    user: {
      avatar_url: 'https://avatars.githubusercontent.com/u/1747664?v=4',
      events_url: 'https://api.github.com/users/BuffaloDrew/events{/privacy}',
      followers_url: 'https://api.github.com/users/BuffaloDrew/followers',
      following_url:
        'https://api.github.com/users/BuffaloDrew/following{/other_user}',
      gists_url: 'https://api.github.com/users/BuffaloDrew/gists{/gist_id}',
      gravatar_id: '',
      html_url: 'https://github.com/BuffaloDrew',
      id: 1747664,
      login: 'BuffaloDrew',
      node_id: 'MDQ6VXNlcjE3NDc2NjQ=',
      organizations_url: 'https://api.github.com/users/BuffaloDrew/orgs',
      received_events_url:
        'https://api.github.com/users/BuffaloDrew/received_events',
      repos_url: 'https://api.github.com/users/BuffaloDrew/repos',
      site_admin: false,
      starred_url:
        'https://api.github.com/users/BuffaloDrew/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/BuffaloDrew/subscriptions',
      type: 'User',
      url: 'https://api.github.com/users/BuffaloDrew',
    },
  },
  issue: {
    active_lock_reason: null,
    assignee: null,
    assignees: [],
    author_association: 'CONTRIBUTOR',
    body: 'Here is my description',
    closed_at: null,
    comments: 1,
    comments_url: 'https://api.github.com/repos/test/test/issues/54/comments',
    created_at: '2022-08-25T17:21:26Z',
    events_url: 'https://api.github.com/repos/test/test/issues/54/events',
    html_url: 'https://github.com/test/test/issues/54',
    id: 1351220757,
    labels: [],
    labels_url:
      'https://api.github.com/repos/test/test/issues/54/labels{/name}',
    locked: false,
    milestone: null,
    node_id: 'I_kwDOHycosM5Qif4V',
    number: TEST_EXTERNAL_ID,
    performed_via_github_app: null,
    reactions: {
      '+1': 0,
      '-1': 0,
      confused: 0,
      eyes: 0,
      heart: 0,
      hooray: 0,
      laugh: 0,
      rocket: 0,
      total_count: 0,
      url: 'https://api.github.com/repos/test/test/issues/54/reactions',
    },
    repository_url: 'https://api.github.com/repos/test/test',
    state: 'open',
    state_reason: null,
    timeline_url: 'https://api.github.com/repos/test/test/issues/54/timeline',
    title: 'New Issue Created',
    updated_at: '2022-08-25T17:33:37Z',
    url: 'https://api.github.com/repos/test/test/issues/54',
    user: {
      avatar_url: 'https://avatars.githubusercontent.com/u/1747664?v=4',
      events_url: 'https://api.github.com/users/BuffaloDrew/events{/privacy}',
      followers_url: 'https://api.github.com/users/BuffaloDrew/followers',
      following_url:
        'https://api.github.com/users/BuffaloDrew/following{/other_user}',
      gists_url: 'https://api.github.com/users/BuffaloDrew/gists{/gist_id}',
      gravatar_id: '',
      html_url: 'https://github.com/BuffaloDrew',
      id: 1747664,
      login: 'BuffaloDrew',
      node_id: 'MDQ6VXNlcjE3NDc2NjQ=',
      organizations_url: 'https://api.github.com/users/BuffaloDrew/orgs',
      received_events_url:
        'https://api.github.com/users/BuffaloDrew/received_events',
      repos_url: 'https://api.github.com/users/BuffaloDrew/repos',
      site_admin: false,
      starred_url:
        'https://api.github.com/users/BuffaloDrew/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/BuffaloDrew/subscriptions',
      type: 'User',
      url: 'https://api.github.com/users/BuffaloDrew',
    },
  },
  organization: {
    avatar_url: 'https://avatars.githubusercontent.com/u/110850163?v=4',
    description: null,
    events_url: 'https://api.github.com/orgs/ui-te-test/events',
    hooks_url: 'https://api.github.com/orgs/ui-te-test/hooks',
    id: 110850163,
    issues_url: 'https://api.github.com/orgs/ui-te-test/issues',
    login: 'ui-te-test',
    members_url: 'https://api.github.com/orgs/ui-te-test/members{/member}',
    node_id: 'O_kgDOBptwcw',
    public_members_url:
      'https://api.github.com/orgs/ui-te-test/public_members{/member}',
    repos_url: 'https://api.github.com/orgs/ui-te-test/repos',
    url: 'https://api.github.com/orgs/ui-te-test',
  },
  repository: {
    allow_forking: false,
    archive_url:
      'https://api.github.com/repos/test/test/{archive_format}{/ref}',
    archived: false,
    assignees_url: 'https://api.github.com/repos/test/test/assignees{/user}',
    blobs_url: 'https://api.github.com/repos/test/test/git/blobs{/sha}',
    branches_url: 'https://api.github.com/repos/test/test/branches{/branch}',
    clone_url: 'https://github.com/test/test.git',
    collaborators_url:
      'https://api.github.com/repos/test/test/collaborators{/collaborator}',
    comments_url: 'https://api.github.com/repos/test/test/comments{/number}',
    commits_url: 'https://api.github.com/repos/test/test/commits{/sha}',
    compare_url:
      'https://api.github.com/repos/test/test/compare/{base}...{head}',
    contents_url: 'https://api.github.com/repos/test/test/contents/{+path}',
    contributors_url: 'https://api.github.com/repos/test/test/contributors',
    created_at: '2022-08-08T18:17:16Z',
    default_branch: 'main',
    deployments_url: 'https://api.github.com/repos/test/test/deployments',
    description: null,
    disabled: false,
    downloads_url: 'https://api.github.com/repos/test/test/downloads',
    events_url: 'https://api.github.com/repos/test/test/events',
    fork: false,
    forks: 0,
    forks_count: 0,
    forks_url: 'https://api.github.com/repos/test/test/forks',
    full_name: 'test/test',
    git_commits_url: 'https://api.github.com/repos/test/test/git/commits{/sha}',
    git_refs_url: 'https://api.github.com/repos/test/test/git/refs{/sha}',
    git_tags_url: 'https://api.github.com/repos/test/test/git/tags{/sha}',
    git_url: 'git://github.com/test/test.git',
    has_downloads: true,
    has_issues: true,
    has_pages: false,
    has_projects: true,
    has_wiki: true,
    homepage: null,
    hooks_url: 'https://api.github.com/repos/test/test/hooks',
    html_url: 'https://github.com/test/test',
    id: 522660016,
    is_template: false,
    issue_comment_url:
      'https://api.github.com/repos/test/test/issues/comments{/number}',
    issue_events_url:
      'https://api.github.com/repos/test/test/issues/events{/number}',
    issues_url: 'https://api.github.com/repos/test/test/issues{/number}',
    keys_url: 'https://api.github.com/repos/test/test/keys{/key_id}',
    labels_url: 'https://api.github.com/repos/test/test/labels{/name}',
    language: null,
    languages_url: 'https://api.github.com/repos/test/test/languages',
    license: null,
    merges_url: 'https://api.github.com/repos/test/test/merges',
    milestones_url:
      'https://api.github.com/repos/test/test/milestones{/number}',
    mirror_url: null,
    name: 'test',
    node_id: 'R_kgDOHycosA',
    notifications_url:
      'https://api.github.com/repos/test/test/notifications{?since,all,participating}',
    open_issues: 32,
    open_issues_count: 32,
    owner: {
      avatar_url: 'https://avatars.githubusercontent.com/u/110850163?v=4',
      events_url: 'https://api.github.com/users/ui-te-test/events{/privacy}',
      followers_url: 'https://api.github.com/users/ui-te-test/followers',
      following_url:
        'https://api.github.com/users/ui-te-test/following{/other_user}',
      gists_url: 'https://api.github.com/users/ui-te-test/gists{/gist_id}',
      gravatar_id: '',
      html_url: 'https://github.com/ui-te-test',
      id: 110850163,
      login: 'ui-te-test',
      node_id: 'O_kgDOBptwcw',
      organizations_url: 'https://api.github.com/users/ui-te-test/orgs',
      received_events_url:
        'https://api.github.com/users/ui-te-test/received_events',
      repos_url: 'https://api.github.com/users/ui-te-test/repos',
      site_admin: false,
      starred_url:
        'https://api.github.com/users/ui-te-test/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/ui-te-test/subscriptions',
      type: 'Organization',
      url: 'https://api.github.com/users/ui-te-test',
    },
    private: true,
    pulls_url: 'https://api.github.com/repos/test/test/pulls{/number}',
    pushed_at: '2022-08-25T14:24:16Z',
    releases_url: 'https://api.github.com/repos/test/test/releases{/id}',
    size: 157,
    ssh_url: 'git@github.com:test/test.git',
    stargazers_count: 0,
    stargazers_url: 'https://api.github.com/repos/test/test/stargazers',
    statuses_url: 'https://api.github.com/repos/test/test/statuses/{sha}',
    subscribers_url: 'https://api.github.com/repos/test/test/subscribers',
    subscription_url: 'https://api.github.com/repos/test/test/subscription',
    svn_url: 'https://github.com/test/test',
    tags_url: 'https://api.github.com/repos/test/test/tags',
    teams_url: 'https://api.github.com/repos/test/test/teams',
    topics: [],
    trees_url: 'https://api.github.com/repos/test/test/git/trees{/sha}',
    updated_at: '2022-08-25T14:23:06Z',
    url: 'https://api.github.com/repos/test/test',
    visibility: 'private',
    watchers: 0,
    watchers_count: 0,
    web_commit_signoff_required: false,
  },
  sender: {
    avatar_url: 'https://avatars.githubusercontent.com/u/1747664?v=4',
    events_url: 'https://api.github.com/users/BuffaloDrew/events{/privacy}',
    followers_url: 'https://api.github.com/users/BuffaloDrew/followers',
    following_url:
      'https://api.github.com/users/BuffaloDrew/following{/other_user}',
    gists_url: 'https://api.github.com/users/BuffaloDrew/gists{/gist_id}',
    gravatar_id: '',
    html_url: 'https://github.com/BuffaloDrew',
    id: 1747664,
    login: 'BuffaloDrew',
    node_id: 'MDQ6VXNlcjE3NDc2NjQ=',
    organizations_url: 'https://api.github.com/users/BuffaloDrew/orgs',
    received_events_url:
      'https://api.github.com/users/BuffaloDrew/received_events',
    repos_url: 'https://api.github.com/users/BuffaloDrew/repos',
    site_admin: false,
    starred_url:
      'https://api.github.com/users/BuffaloDrew/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/BuffaloDrew/subscriptions',
    type: 'User',
    url: 'https://api.github.com/users/BuffaloDrew',
  },
};

const CLOSED = {
  action: 'closed',
  issue: {
    active_lock_reason: null,
    assignee: null,
    assignees: [],
    author_association: 'CONTRIBUTOR',
    body: 'Here is my description',
    closed_at: '2022-08-25T17:39:07Z',
    comments: 1,
    comments_url: 'https://api.github.com/repos/test/test/issues/54/comments',
    created_at: '2022-08-25T17:21:26Z',
    events_url: 'https://api.github.com/repos/test/test/issues/54/events',
    html_url: 'https://github.com/test/test/issues/54',
    id: 1351220757,
    labels: [],
    labels_url:
      'https://api.github.com/repos/test/test/issues/54/labels{/name}',
    locked: false,
    milestone: null,
    node_id: 'I_kwDOHycosM5Qif4V',
    number: TEST_EXTERNAL_ID,
    performed_via_github_app: null,
    reactions: {
      '+1': 0,
      '-1': 0,
      confused: 0,
      eyes: 0,
      heart: 0,
      hooray: 0,
      laugh: 0,
      rocket: 0,
      total_count: 0,
      url: 'https://api.github.com/repos/test/test/issues/54/reactions',
    },
    repository_url: 'https://api.github.com/repos/test/test',
    state: 'closed',
    state_reason: 'completed',
    timeline_url: 'https://api.github.com/repos/test/test/issues/54/timeline',
    title: 'New Issue Created',
    updated_at: '2022-08-25T17:39:07Z',
    url: 'https://api.github.com/repos/test/test/issues/54',
    user: {
      avatar_url: 'https://avatars.githubusercontent.com/u/1747664?v=4',
      events_url: 'https://api.github.com/users/BuffaloDrew/events{/privacy}',
      followers_url: 'https://api.github.com/users/BuffaloDrew/followers',
      following_url:
        'https://api.github.com/users/BuffaloDrew/following{/other_user}',
      gists_url: 'https://api.github.com/users/BuffaloDrew/gists{/gist_id}',
      gravatar_id: '',
      html_url: 'https://github.com/BuffaloDrew',
      id: 1747664,
      login: 'BuffaloDrew',
      node_id: 'MDQ6VXNlcjE3NDc2NjQ=',
      organizations_url: 'https://api.github.com/users/BuffaloDrew/orgs',
      received_events_url:
        'https://api.github.com/users/BuffaloDrew/received_events',
      repos_url: 'https://api.github.com/users/BuffaloDrew/repos',
      site_admin: false,
      starred_url:
        'https://api.github.com/users/BuffaloDrew/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/BuffaloDrew/subscriptions',
      type: 'User',
      url: 'https://api.github.com/users/BuffaloDrew',
    },
  },
  organization: {
    avatar_url: 'https://avatars.githubusercontent.com/u/110850163?v=4',
    description: null,
    events_url: 'https://api.github.com/orgs/ui-te-test/events',
    hooks_url: 'https://api.github.com/orgs/ui-te-test/hooks',
    id: 110850163,
    issues_url: 'https://api.github.com/orgs/ui-te-test/issues',
    login: 'ui-te-test',
    members_url: 'https://api.github.com/orgs/ui-te-test/members{/member}',
    node_id: 'O_kgDOBptwcw',
    public_members_url:
      'https://api.github.com/orgs/ui-te-test/public_members{/member}',
    repos_url: 'https://api.github.com/orgs/ui-te-test/repos',
    url: 'https://api.github.com/orgs/ui-te-test',
  },
  repository: {
    allow_forking: false,
    archive_url:
      'https://api.github.com/repos/test/test/{archive_format}{/ref}',
    archived: false,
    assignees_url: 'https://api.github.com/repos/test/test/assignees{/user}',
    blobs_url: 'https://api.github.com/repos/test/test/git/blobs{/sha}',
    branches_url: 'https://api.github.com/repos/test/test/branches{/branch}',
    clone_url: 'https://github.com/test/test.git',
    collaborators_url:
      'https://api.github.com/repos/test/test/collaborators{/collaborator}',
    comments_url: 'https://api.github.com/repos/test/test/comments{/number}',
    commits_url: 'https://api.github.com/repos/test/test/commits{/sha}',
    compare_url:
      'https://api.github.com/repos/test/test/compare/{base}...{head}',
    contents_url: 'https://api.github.com/repos/test/test/contents/{+path}',
    contributors_url: 'https://api.github.com/repos/test/test/contributors',
    created_at: '2022-08-08T18:17:16Z',
    default_branch: 'main',
    deployments_url: 'https://api.github.com/repos/test/test/deployments',
    description: null,
    disabled: false,
    downloads_url: 'https://api.github.com/repos/test/test/downloads',
    events_url: 'https://api.github.com/repos/test/test/events',
    fork: false,
    forks: 0,
    forks_count: 0,
    forks_url: 'https://api.github.com/repos/test/test/forks',
    full_name: 'test/test',
    git_commits_url: 'https://api.github.com/repos/test/test/git/commits{/sha}',
    git_refs_url: 'https://api.github.com/repos/test/test/git/refs{/sha}',
    git_tags_url: 'https://api.github.com/repos/test/test/git/tags{/sha}',
    git_url: 'git://github.com/test/test.git',
    has_downloads: true,
    has_issues: true,
    has_pages: false,
    has_projects: true,
    has_wiki: true,
    homepage: null,
    hooks_url: 'https://api.github.com/repos/test/test/hooks',
    html_url: 'https://github.com/test/test',
    id: 522660016,
    is_template: false,
    issue_comment_url:
      'https://api.github.com/repos/test/test/issues/comments{/number}',
    issue_events_url:
      'https://api.github.com/repos/test/test/issues/events{/number}',
    issues_url: 'https://api.github.com/repos/test/test/issues{/number}',
    keys_url: 'https://api.github.com/repos/test/test/keys{/key_id}',
    labels_url: 'https://api.github.com/repos/test/test/labels{/name}',
    language: null,
    languages_url: 'https://api.github.com/repos/test/test/languages',
    license: null,
    merges_url: 'https://api.github.com/repos/test/test/merges',
    milestones_url:
      'https://api.github.com/repos/test/test/milestones{/number}',
    mirror_url: null,
    name: 'test',
    node_id: 'R_kgDOHycosA',
    notifications_url:
      'https://api.github.com/repos/test/test/notifications{?since,all,participating}',
    open_issues: 31,
    open_issues_count: 31,
    owner: {
      avatar_url: 'https://avatars.githubusercontent.com/u/110850163?v=4',
      events_url: 'https://api.github.com/users/ui-te-test/events{/privacy}',
      followers_url: 'https://api.github.com/users/ui-te-test/followers',
      following_url:
        'https://api.github.com/users/ui-te-test/following{/other_user}',
      gists_url: 'https://api.github.com/users/ui-te-test/gists{/gist_id}',
      gravatar_id: '',
      html_url: 'https://github.com/ui-te-test',
      id: 110850163,
      login: 'ui-te-test',
      node_id: 'O_kgDOBptwcw',
      organizations_url: 'https://api.github.com/users/ui-te-test/orgs',
      received_events_url:
        'https://api.github.com/users/ui-te-test/received_events',
      repos_url: 'https://api.github.com/users/ui-te-test/repos',
      site_admin: false,
      starred_url:
        'https://api.github.com/users/ui-te-test/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/ui-te-test/subscriptions',
      type: 'Organization',
      url: 'https://api.github.com/users/ui-te-test',
    },
    private: true,
    pulls_url: 'https://api.github.com/repos/test/test/pulls{/number}',
    pushed_at: '2022-08-25T14:24:16Z',
    releases_url: 'https://api.github.com/repos/test/test/releases{/id}',
    size: 157,
    ssh_url: 'git@github.com:test/test.git',
    stargazers_count: 0,
    stargazers_url: 'https://api.github.com/repos/test/test/stargazers',
    statuses_url: 'https://api.github.com/repos/test/test/statuses/{sha}',
    subscribers_url: 'https://api.github.com/repos/test/test/subscribers',
    subscription_url: 'https://api.github.com/repos/test/test/subscription',
    svn_url: 'https://github.com/test/test',
    tags_url: 'https://api.github.com/repos/test/test/tags',
    teams_url: 'https://api.github.com/repos/test/test/teams',
    topics: [],
    trees_url: 'https://api.github.com/repos/test/test/git/trees{/sha}',
    updated_at: '2022-08-25T14:23:06Z',
    url: 'https://api.github.com/repos/test/test',
    visibility: 'private',
    watchers: 0,
    watchers_count: 0,
    web_commit_signoff_required: false,
  },
  sender: {
    avatar_url: 'https://avatars.githubusercontent.com/u/1747664?v=4',
    events_url: 'https://api.github.com/users/BuffaloDrew/events{/privacy}',
    followers_url: 'https://api.github.com/users/BuffaloDrew/followers',
    following_url:
      'https://api.github.com/users/BuffaloDrew/following{/other_user}',
    gists_url: 'https://api.github.com/users/BuffaloDrew/gists{/gist_id}',
    gravatar_id: '',
    html_url: 'https://github.com/BuffaloDrew',
    id: 1747664,
    login: 'BuffaloDrew',
    node_id: 'MDQ6VXNlcjE3NDc2NjQ=',
    organizations_url: 'https://api.github.com/users/BuffaloDrew/orgs',
    received_events_url:
      'https://api.github.com/users/BuffaloDrew/received_events',
    repos_url: 'https://api.github.com/users/BuffaloDrew/repos',
    site_admin: false,
    starred_url:
      'https://api.github.com/users/BuffaloDrew/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/BuffaloDrew/subscriptions',
    type: 'User',
    url: 'https://api.github.com/users/BuffaloDrew',
  },
};

const REOPENED = {
  action: 'reopened',
  issue: {
    active_lock_reason: null,
    assignee: null,
    assignees: [],
    author_association: 'CONTRIBUTOR',
    body: 'Here is my description',
    closed_at: null,
    comments: 1,
    comments_url: 'https://api.github.com/repos/test/test/issues/54/comments',
    created_at: '2022-08-25T17:21:26Z',
    events_url: 'https://api.github.com/repos/test/test/issues/54/events',
    html_url: 'https://github.com/test/test/issues/54',
    id: 1351220757,
    labels: [],
    labels_url:
      'https://api.github.com/repos/test/test/issues/54/labels{/name}',
    locked: false,
    milestone: null,
    node_id: 'I_kwDOHycosM5Qif4V',
    number: TEST_EXTERNAL_ID,
    performed_via_github_app: null,
    reactions: {
      '+1': 0,
      '-1': 0,
      confused: 0,
      eyes: 0,
      heart: 0,
      hooray: 0,
      laugh: 0,
      rocket: 0,
      total_count: 0,
      url: 'https://api.github.com/repos/test/test/issues/54/reactions',
    },
    repository_url: 'https://api.github.com/repos/test/test',
    state: 'open',
    state_reason: 'reopened',
    timeline_url: 'https://api.github.com/repos/test/test/issues/54/timeline',
    title: 'New Issue Created',
    updated_at: '2022-08-25T17:39:09Z',
    url: 'https://api.github.com/repos/test/test/issues/54',
    user: {
      avatar_url: 'https://avatars.githubusercontent.com/u/1747664?v=4',
      events_url: 'https://api.github.com/users/BuffaloDrew/events{/privacy}',
      followers_url: 'https://api.github.com/users/BuffaloDrew/followers',
      following_url:
        'https://api.github.com/users/BuffaloDrew/following{/other_user}',
      gists_url: 'https://api.github.com/users/BuffaloDrew/gists{/gist_id}',
      gravatar_id: '',
      html_url: 'https://github.com/BuffaloDrew',
      id: 1747664,
      login: 'BuffaloDrew',
      node_id: 'MDQ6VXNlcjE3NDc2NjQ=',
      organizations_url: 'https://api.github.com/users/BuffaloDrew/orgs',
      received_events_url:
        'https://api.github.com/users/BuffaloDrew/received_events',
      repos_url: 'https://api.github.com/users/BuffaloDrew/repos',
      site_admin: false,
      starred_url:
        'https://api.github.com/users/BuffaloDrew/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/BuffaloDrew/subscriptions',
      type: 'User',
      url: 'https://api.github.com/users/BuffaloDrew',
    },
  },
  organization: {
    avatar_url: 'https://avatars.githubusercontent.com/u/110850163?v=4',
    description: null,
    events_url: 'https://api.github.com/orgs/ui-te-test/events',
    hooks_url: 'https://api.github.com/orgs/ui-te-test/hooks',
    id: 110850163,
    issues_url: 'https://api.github.com/orgs/ui-te-test/issues',
    login: 'ui-te-test',
    members_url: 'https://api.github.com/orgs/ui-te-test/members{/member}',
    node_id: 'O_kgDOBptwcw',
    public_members_url:
      'https://api.github.com/orgs/ui-te-test/public_members{/member}',
    repos_url: 'https://api.github.com/orgs/ui-te-test/repos',
    url: 'https://api.github.com/orgs/ui-te-test',
  },
  repository: {
    allow_forking: false,
    archive_url:
      'https://api.github.com/repos/test/test/{archive_format}{/ref}',
    archived: false,
    assignees_url: 'https://api.github.com/repos/test/test/assignees{/user}',
    blobs_url: 'https://api.github.com/repos/test/test/git/blobs{/sha}',
    branches_url: 'https://api.github.com/repos/test/test/branches{/branch}',
    clone_url: 'https://github.com/test/test.git',
    collaborators_url:
      'https://api.github.com/repos/test/test/collaborators{/collaborator}',
    comments_url: 'https://api.github.com/repos/test/test/comments{/number}',
    commits_url: 'https://api.github.com/repos/test/test/commits{/sha}',
    compare_url:
      'https://api.github.com/repos/test/test/compare/{base}...{head}',
    contents_url: 'https://api.github.com/repos/test/test/contents/{+path}',
    contributors_url: 'https://api.github.com/repos/test/test/contributors',
    created_at: '2022-08-08T18:17:16Z',
    default_branch: 'main',
    deployments_url: 'https://api.github.com/repos/test/test/deployments',
    description: null,
    disabled: false,
    downloads_url: 'https://api.github.com/repos/test/test/downloads',
    events_url: 'https://api.github.com/repos/test/test/events',
    fork: false,
    forks: 0,
    forks_count: 0,
    forks_url: 'https://api.github.com/repos/test/test/forks',
    full_name: 'test/test',
    git_commits_url: 'https://api.github.com/repos/test/test/git/commits{/sha}',
    git_refs_url: 'https://api.github.com/repos/test/test/git/refs{/sha}',
    git_tags_url: 'https://api.github.com/repos/test/test/git/tags{/sha}',
    git_url: 'git://github.com/test/test.git',
    has_downloads: true,
    has_issues: true,
    has_pages: false,
    has_projects: true,
    has_wiki: true,
    homepage: null,
    hooks_url: 'https://api.github.com/repos/test/test/hooks',
    html_url: 'https://github.com/test/test',
    id: 522660016,
    is_template: false,
    issue_comment_url:
      'https://api.github.com/repos/test/test/issues/comments{/number}',
    issue_events_url:
      'https://api.github.com/repos/test/test/issues/events{/number}',
    issues_url: 'https://api.github.com/repos/test/test/issues{/number}',
    keys_url: 'https://api.github.com/repos/test/test/keys{/key_id}',
    labels_url: 'https://api.github.com/repos/test/test/labels{/name}',
    language: null,
    languages_url: 'https://api.github.com/repos/test/test/languages',
    license: null,
    merges_url: 'https://api.github.com/repos/test/test/merges',
    milestones_url:
      'https://api.github.com/repos/test/test/milestones{/number}',
    mirror_url: null,
    name: 'test',
    node_id: 'R_kgDOHycosA',
    notifications_url:
      'https://api.github.com/repos/test/test/notifications{?since,all,participating}',
    open_issues: 32,
    open_issues_count: 32,
    owner: {
      avatar_url: 'https://avatars.githubusercontent.com/u/110850163?v=4',
      events_url: 'https://api.github.com/users/ui-te-test/events{/privacy}',
      followers_url: 'https://api.github.com/users/ui-te-test/followers',
      following_url:
        'https://api.github.com/users/ui-te-test/following{/other_user}',
      gists_url: 'https://api.github.com/users/ui-te-test/gists{/gist_id}',
      gravatar_id: '',
      html_url: 'https://github.com/ui-te-test',
      id: 110850163,
      login: 'ui-te-test',
      node_id: 'O_kgDOBptwcw',
      organizations_url: 'https://api.github.com/users/ui-te-test/orgs',
      received_events_url:
        'https://api.github.com/users/ui-te-test/received_events',
      repos_url: 'https://api.github.com/users/ui-te-test/repos',
      site_admin: false,
      starred_url:
        'https://api.github.com/users/ui-te-test/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/ui-te-test/subscriptions',
      type: 'Organization',
      url: 'https://api.github.com/users/ui-te-test',
    },
    private: true,
    pulls_url: 'https://api.github.com/repos/test/test/pulls{/number}',
    pushed_at: '2022-08-25T14:24:16Z',
    releases_url: 'https://api.github.com/repos/test/test/releases{/id}',
    size: 157,
    ssh_url: 'git@github.com:test/test.git',
    stargazers_count: 0,
    stargazers_url: 'https://api.github.com/repos/test/test/stargazers',
    statuses_url: 'https://api.github.com/repos/test/test/statuses/{sha}',
    subscribers_url: 'https://api.github.com/repos/test/test/subscribers',
    subscription_url: 'https://api.github.com/repos/test/test/subscription',
    svn_url: 'https://github.com/test/test',
    tags_url: 'https://api.github.com/repos/test/test/tags',
    teams_url: 'https://api.github.com/repos/test/test/teams',
    topics: [],
    trees_url: 'https://api.github.com/repos/test/test/git/trees{/sha}',
    updated_at: '2022-08-25T14:23:06Z',
    url: 'https://api.github.com/repos/test/test',
    visibility: 'private',
    watchers: 0,
    watchers_count: 0,
    web_commit_signoff_required: false,
  },
  sender: {
    avatar_url: 'https://avatars.githubusercontent.com/u/1747664?v=4',
    events_url: 'https://api.github.com/users/BuffaloDrew/events{/privacy}',
    followers_url: 'https://api.github.com/users/BuffaloDrew/followers',
    following_url:
      'https://api.github.com/users/BuffaloDrew/following{/other_user}',
    gists_url: 'https://api.github.com/users/BuffaloDrew/gists{/gist_id}',
    gravatar_id: '',
    html_url: 'https://github.com/BuffaloDrew',
    id: 1747664,
    login: 'BuffaloDrew',
    node_id: 'MDQ6VXNlcjE3NDc2NjQ=',
    organizations_url: 'https://api.github.com/users/BuffaloDrew/orgs',
    received_events_url:
      'https://api.github.com/users/BuffaloDrew/received_events',
    repos_url: 'https://api.github.com/users/BuffaloDrew/repos',
    site_admin: false,
    starred_url:
      'https://api.github.com/users/BuffaloDrew/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/BuffaloDrew/subscriptions',
    type: 'User',
    url: 'https://api.github.com/users/BuffaloDrew',
  },
};

const UNLABELED = {
  action: 'unlabeled',
  issue: {
    active_lock_reason: null,
    assignee: null,
    assignees: [],
    author_association: 'CONTRIBUTOR',
    body: 'Here is my description',
    closed_at: null,
    comments: 1,
    comments_url: 'https://api.github.com/repos/test/test/issues/54/comments',
    created_at: '2022-08-25T17:21:26Z',
    events_url: 'https://api.github.com/repos/test/test/issues/54/events',
    html_url: 'https://github.com/test/test/issues/54',
    id: 1351220757,
    labels: [],
    labels_url:
      'https://api.github.com/repos/test/test/issues/54/labels{/name}',
    locked: false,
    milestone: null,
    node_id: 'I_kwDOHycosM5Qif4V',
    number: TEST_EXTERNAL_ID,
    performed_via_github_app: null,
    reactions: {
      '+1': 0,
      '-1': 0,
      confused: 0,
      eyes: 0,
      heart: 0,
      hooray: 0,
      laugh: 0,
      rocket: 0,
      total_count: 0,
      url: 'https://api.github.com/repos/test/test/issues/54/reactions',
    },
    repository_url: 'https://api.github.com/repos/test/test',
    state: 'open',
    state_reason: 'reopened',
    timeline_url: 'https://api.github.com/repos/test/test/issues/54/timeline',
    title: 'New Issue Created',
    updated_at: '2022-08-25T17:52:15Z',
    url: 'https://api.github.com/repos/test/test/issues/54',
    user: {
      avatar_url: 'https://avatars.githubusercontent.com/u/1747664?v=4',
      events_url: 'https://api.github.com/users/BuffaloDrew/events{/privacy}',
      followers_url: 'https://api.github.com/users/BuffaloDrew/followers',
      following_url:
        'https://api.github.com/users/BuffaloDrew/following{/other_user}',
      gists_url: 'https://api.github.com/users/BuffaloDrew/gists{/gist_id}',
      gravatar_id: '',
      html_url: 'https://github.com/BuffaloDrew',
      id: 1747664,
      login: 'BuffaloDrew',
      node_id: 'MDQ6VXNlcjE3NDc2NjQ=',
      organizations_url: 'https://api.github.com/users/BuffaloDrew/orgs',
      received_events_url:
        'https://api.github.com/users/BuffaloDrew/received_events',
      repos_url: 'https://api.github.com/users/BuffaloDrew/repos',
      site_admin: false,
      starred_url:
        'https://api.github.com/users/BuffaloDrew/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/BuffaloDrew/subscriptions',
      type: 'User',
      url: 'https://api.github.com/users/BuffaloDrew',
    },
  },
  label: {
    color: 'B02FDC',
    default: false,
    description: '',
    id: 4463926691,
    name: 'test',
    node_id: 'LA_kwDOHycosM8AAAABChIdow',
    url: 'https://api.github.com/repos/test/test/labels/test',
  },
  organization: {
    avatar_url: 'https://avatars.githubusercontent.com/u/110850163?v=4',
    description: null,
    events_url: 'https://api.github.com/orgs/ui-te-test/events',
    hooks_url: 'https://api.github.com/orgs/ui-te-test/hooks',
    id: 110850163,
    issues_url: 'https://api.github.com/orgs/ui-te-test/issues',
    login: 'ui-te-test',
    members_url: 'https://api.github.com/orgs/ui-te-test/members{/member}',
    node_id: 'O_kgDOBptwcw',
    public_members_url:
      'https://api.github.com/orgs/ui-te-test/public_members{/member}',
    repos_url: 'https://api.github.com/orgs/ui-te-test/repos',
    url: 'https://api.github.com/orgs/ui-te-test',
  },
  repository: {
    allow_forking: false,
    archive_url:
      'https://api.github.com/repos/test/test/{archive_format}{/ref}',
    archived: false,
    assignees_url: 'https://api.github.com/repos/test/test/assignees{/user}',
    blobs_url: 'https://api.github.com/repos/test/test/git/blobs{/sha}',
    branches_url: 'https://api.github.com/repos/test/test/branches{/branch}',
    clone_url: 'https://github.com/test/test.git',
    collaborators_url:
      'https://api.github.com/repos/test/test/collaborators{/collaborator}',
    comments_url: 'https://api.github.com/repos/test/test/comments{/number}',
    commits_url: 'https://api.github.com/repos/test/test/commits{/sha}',
    compare_url:
      'https://api.github.com/repos/test/test/compare/{base}...{head}',
    contents_url: 'https://api.github.com/repos/test/test/contents/{+path}',
    contributors_url: 'https://api.github.com/repos/test/test/contributors',
    created_at: '2022-08-08T18:17:16Z',
    default_branch: 'main',
    deployments_url: 'https://api.github.com/repos/test/test/deployments',
    description: null,
    disabled: false,
    downloads_url: 'https://api.github.com/repos/test/test/downloads',
    events_url: 'https://api.github.com/repos/test/test/events',
    fork: false,
    forks: 0,
    forks_count: 0,
    forks_url: 'https://api.github.com/repos/test/test/forks',
    full_name: 'test/test',
    git_commits_url: 'https://api.github.com/repos/test/test/git/commits{/sha}',
    git_refs_url: 'https://api.github.com/repos/test/test/git/refs{/sha}',
    git_tags_url: 'https://api.github.com/repos/test/test/git/tags{/sha}',
    git_url: 'git://github.com/test/test.git',
    has_downloads: true,
    has_issues: true,
    has_pages: false,
    has_projects: true,
    has_wiki: true,
    homepage: null,
    hooks_url: 'https://api.github.com/repos/test/test/hooks',
    html_url: 'https://github.com/test/test',
    id: 522660016,
    is_template: false,
    issue_comment_url:
      'https://api.github.com/repos/test/test/issues/comments{/number}',
    issue_events_url:
      'https://api.github.com/repos/test/test/issues/events{/number}',
    issues_url: 'https://api.github.com/repos/test/test/issues{/number}',
    keys_url: 'https://api.github.com/repos/test/test/keys{/key_id}',
    labels_url: 'https://api.github.com/repos/test/test/labels{/name}',
    language: null,
    languages_url: 'https://api.github.com/repos/test/test/languages',
    license: null,
    merges_url: 'https://api.github.com/repos/test/test/merges',
    milestones_url:
      'https://api.github.com/repos/test/test/milestones{/number}',
    mirror_url: null,
    name: 'test',
    node_id: 'R_kgDOHycosA',
    notifications_url:
      'https://api.github.com/repos/test/test/notifications{?since,all,participating}',
    open_issues: 32,
    open_issues_count: 32,
    owner: {
      avatar_url: 'https://avatars.githubusercontent.com/u/110850163?v=4',
      events_url: 'https://api.github.com/users/ui-te-test/events{/privacy}',
      followers_url: 'https://api.github.com/users/ui-te-test/followers',
      following_url:
        'https://api.github.com/users/ui-te-test/following{/other_user}',
      gists_url: 'https://api.github.com/users/ui-te-test/gists{/gist_id}',
      gravatar_id: '',
      html_url: 'https://github.com/ui-te-test',
      id: 110850163,
      login: 'ui-te-test',
      node_id: 'O_kgDOBptwcw',
      organizations_url: 'https://api.github.com/users/ui-te-test/orgs',
      received_events_url:
        'https://api.github.com/users/ui-te-test/received_events',
      repos_url: 'https://api.github.com/users/ui-te-test/repos',
      site_admin: false,
      starred_url:
        'https://api.github.com/users/ui-te-test/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/ui-te-test/subscriptions',
      type: 'Organization',
      url: 'https://api.github.com/users/ui-te-test',
    },
    private: true,
    pulls_url: 'https://api.github.com/repos/test/test/pulls{/number}',
    pushed_at: '2022-08-25T14:24:16Z',
    releases_url: 'https://api.github.com/repos/test/test/releases{/id}',
    size: 157,
    ssh_url: 'git@github.com:test/test.git',
    stargazers_count: 0,
    stargazers_url: 'https://api.github.com/repos/test/test/stargazers',
    statuses_url: 'https://api.github.com/repos/test/test/statuses/{sha}',
    subscribers_url: 'https://api.github.com/repos/test/test/subscribers',
    subscription_url: 'https://api.github.com/repos/test/test/subscription',
    svn_url: 'https://github.com/test/test',
    tags_url: 'https://api.github.com/repos/test/test/tags',
    teams_url: 'https://api.github.com/repos/test/test/teams',
    topics: [],
    trees_url: 'https://api.github.com/repos/test/test/git/trees{/sha}',
    updated_at: '2022-08-25T14:23:06Z',
    url: 'https://api.github.com/repos/test/test',
    visibility: 'private',
    watchers: 0,
    watchers_count: 0,
    web_commit_signoff_required: false,
  },
  sender: {
    avatar_url: 'https://avatars.githubusercontent.com/u/1747664?v=4',
    events_url: 'https://api.github.com/users/BuffaloDrew/events{/privacy}',
    followers_url: 'https://api.github.com/users/BuffaloDrew/followers',
    following_url:
      'https://api.github.com/users/BuffaloDrew/following{/other_user}',
    gists_url: 'https://api.github.com/users/BuffaloDrew/gists{/gist_id}',
    gravatar_id: '',
    html_url: 'https://github.com/BuffaloDrew',
    id: 1747664,
    login: 'BuffaloDrew',
    node_id: 'MDQ6VXNlcjE3NDc2NjQ=',
    organizations_url: 'https://api.github.com/users/BuffaloDrew/orgs',
    received_events_url:
      'https://api.github.com/users/BuffaloDrew/received_events',
    repos_url: 'https://api.github.com/users/BuffaloDrew/repos',
    site_admin: false,
    starred_url:
      'https://api.github.com/users/BuffaloDrew/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/BuffaloDrew/subscriptions',
    type: 'User',
    url: 'https://api.github.com/users/BuffaloDrew',
  },
};

const EDITED = {
  action: 'edited',
  changes: { body: { from: 'Here is my description' } },
  issue: {
    active_lock_reason: null,
    assignee: null,
    assignees: [],
    author_association: 'CONTRIBUTOR',
    body: 'Edited Description!',
    closed_at: null,
    comments: 1,
    comments_url: 'https://api.github.com/repos/test/test/issues/54/comments',
    created_at: '2022-08-25T17:21:26Z',
    events_url: 'https://api.github.com/repos/test/test/issues/54/events',
    html_url: 'https://github.com/test/test/issues/54',
    id: 1351220757,
    labels: [],
    labels_url:
      'https://api.github.com/repos/test/test/issues/54/labels{/name}',
    locked: false,
    milestone: null,
    node_id: 'I_kwDOHycosM5Qif4V',
    number: TEST_EXTERNAL_ID,
    performed_via_github_app: null,
    reactions: {
      '+1': 0,
      '-1': 0,
      confused: 0,
      eyes: 0,
      heart: 0,
      hooray: 0,
      laugh: 0,
      rocket: 0,
      total_count: 0,
      url: 'https://api.github.com/repos/test/test/issues/54/reactions',
    },
    repository_url: 'https://api.github.com/repos/test/test',
    state: 'open',
    state_reason: 'reopened',
    timeline_url: 'https://api.github.com/repos/test/test/issues/54/timeline',
    title: 'New Issue Created',
    updated_at: '2022-08-25T18:02:05Z',
    url: 'https://api.github.com/repos/test/test/issues/54',
    user: {
      avatar_url: 'https://avatars.githubusercontent.com/u/1747664?v=4',
      events_url: 'https://api.github.com/users/BuffaloDrew/events{/privacy}',
      followers_url: 'https://api.github.com/users/BuffaloDrew/followers',
      following_url:
        'https://api.github.com/users/BuffaloDrew/following{/other_user}',
      gists_url: 'https://api.github.com/users/BuffaloDrew/gists{/gist_id}',
      gravatar_id: '',
      html_url: 'https://github.com/BuffaloDrew',
      id: 1747664,
      login: 'BuffaloDrew',
      node_id: 'MDQ6VXNlcjE3NDc2NjQ=',
      organizations_url: 'https://api.github.com/users/BuffaloDrew/orgs',
      received_events_url:
        'https://api.github.com/users/BuffaloDrew/received_events',
      repos_url: 'https://api.github.com/users/BuffaloDrew/repos',
      site_admin: false,
      starred_url:
        'https://api.github.com/users/BuffaloDrew/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/BuffaloDrew/subscriptions',
      type: 'User',
      url: 'https://api.github.com/users/BuffaloDrew',
    },
  },
  organization: {
    avatar_url: 'https://avatars.githubusercontent.com/u/110850163?v=4',
    description: null,
    events_url: 'https://api.github.com/orgs/ui-te-test/events',
    hooks_url: 'https://api.github.com/orgs/ui-te-test/hooks',
    id: 110850163,
    issues_url: 'https://api.github.com/orgs/ui-te-test/issues',
    login: 'ui-te-test',
    members_url: 'https://api.github.com/orgs/ui-te-test/members{/member}',
    node_id: 'O_kgDOBptwcw',
    public_members_url:
      'https://api.github.com/orgs/ui-te-test/public_members{/member}',
    repos_url: 'https://api.github.com/orgs/ui-te-test/repos',
    url: 'https://api.github.com/orgs/ui-te-test',
  },
  repository: {
    allow_forking: false,
    archive_url:
      'https://api.github.com/repos/test/test/{archive_format}{/ref}',
    archived: false,
    assignees_url: 'https://api.github.com/repos/test/test/assignees{/user}',
    blobs_url: 'https://api.github.com/repos/test/test/git/blobs{/sha}',
    branches_url: 'https://api.github.com/repos/test/test/branches{/branch}',
    clone_url: 'https://github.com/test/test.git',
    collaborators_url:
      'https://api.github.com/repos/test/test/collaborators{/collaborator}',
    comments_url: 'https://api.github.com/repos/test/test/comments{/number}',
    commits_url: 'https://api.github.com/repos/test/test/commits{/sha}',
    compare_url:
      'https://api.github.com/repos/test/test/compare/{base}...{head}',
    contents_url: 'https://api.github.com/repos/test/test/contents/{+path}',
    contributors_url: 'https://api.github.com/repos/test/test/contributors',
    created_at: '2022-08-08T18:17:16Z',
    default_branch: 'main',
    deployments_url: 'https://api.github.com/repos/test/test/deployments',
    description: null,
    disabled: false,
    downloads_url: 'https://api.github.com/repos/test/test/downloads',
    events_url: 'https://api.github.com/repos/test/test/events',
    fork: false,
    forks: 0,
    forks_count: 0,
    forks_url: 'https://api.github.com/repos/test/test/forks',
    full_name: 'test/test',
    git_commits_url: 'https://api.github.com/repos/test/test/git/commits{/sha}',
    git_refs_url: 'https://api.github.com/repos/test/test/git/refs{/sha}',
    git_tags_url: 'https://api.github.com/repos/test/test/git/tags{/sha}',
    git_url: 'git://github.com/test/test.git',
    has_downloads: true,
    has_issues: true,
    has_pages: false,
    has_projects: true,
    has_wiki: true,
    homepage: null,
    hooks_url: 'https://api.github.com/repos/test/test/hooks',
    html_url: 'https://github.com/test/test',
    id: 522660016,
    is_template: false,
    issue_comment_url:
      'https://api.github.com/repos/test/test/issues/comments{/number}',
    issue_events_url:
      'https://api.github.com/repos/test/test/issues/events{/number}',
    issues_url: 'https://api.github.com/repos/test/test/issues{/number}',
    keys_url: 'https://api.github.com/repos/test/test/keys{/key_id}',
    labels_url: 'https://api.github.com/repos/test/test/labels{/name}',
    language: null,
    languages_url: 'https://api.github.com/repos/test/test/languages',
    license: null,
    merges_url: 'https://api.github.com/repos/test/test/merges',
    milestones_url:
      'https://api.github.com/repos/test/test/milestones{/number}',
    mirror_url: null,
    name: 'test',
    node_id: 'R_kgDOHycosA',
    notifications_url:
      'https://api.github.com/repos/test/test/notifications{?since,all,participating}',
    open_issues: 32,
    open_issues_count: 32,
    owner: {
      avatar_url: 'https://avatars.githubusercontent.com/u/110850163?v=4',
      events_url: 'https://api.github.com/users/ui-te-test/events{/privacy}',
      followers_url: 'https://api.github.com/users/ui-te-test/followers',
      following_url:
        'https://api.github.com/users/ui-te-test/following{/other_user}',
      gists_url: 'https://api.github.com/users/ui-te-test/gists{/gist_id}',
      gravatar_id: '',
      html_url: 'https://github.com/ui-te-test',
      id: 110850163,
      login: 'ui-te-test',
      node_id: 'O_kgDOBptwcw',
      organizations_url: 'https://api.github.com/users/ui-te-test/orgs',
      received_events_url:
        'https://api.github.com/users/ui-te-test/received_events',
      repos_url: 'https://api.github.com/users/ui-te-test/repos',
      site_admin: false,
      starred_url:
        'https://api.github.com/users/ui-te-test/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/ui-te-test/subscriptions',
      type: 'Organization',
      url: 'https://api.github.com/users/ui-te-test',
    },
    private: true,
    pulls_url: 'https://api.github.com/repos/test/test/pulls{/number}',
    pushed_at: '2022-08-25T14:24:16Z',
    releases_url: 'https://api.github.com/repos/test/test/releases{/id}',
    size: 157,
    ssh_url: 'git@github.com:test/test.git',
    stargazers_count: 0,
    stargazers_url: 'https://api.github.com/repos/test/test/stargazers',
    statuses_url: 'https://api.github.com/repos/test/test/statuses/{sha}',
    subscribers_url: 'https://api.github.com/repos/test/test/subscribers',
    subscription_url: 'https://api.github.com/repos/test/test/subscription',
    svn_url: 'https://github.com/test/test',
    tags_url: 'https://api.github.com/repos/test/test/tags',
    teams_url: 'https://api.github.com/repos/test/test/teams',
    topics: [],
    trees_url: 'https://api.github.com/repos/test/test/git/trees{/sha}',
    updated_at: '2022-08-25T14:23:06Z',
    url: 'https://api.github.com/repos/test/test',
    visibility: 'private',
    watchers: 0,
    watchers_count: 0,
    web_commit_signoff_required: false,
  },
  sender: {
    avatar_url: 'https://avatars.githubusercontent.com/u/1747664?v=4',
    events_url: 'https://api.github.com/users/BuffaloDrew/events{/privacy}',
    followers_url: 'https://api.github.com/users/BuffaloDrew/followers',
    following_url:
      'https://api.github.com/users/BuffaloDrew/following{/other_user}',
    gists_url: 'https://api.github.com/users/BuffaloDrew/gists{/gist_id}',
    gravatar_id: '',
    html_url: 'https://github.com/BuffaloDrew',
    id: 1747664,
    login: 'BuffaloDrew',
    node_id: 'MDQ6VXNlcjE3NDc2NjQ=',
    organizations_url: 'https://api.github.com/users/BuffaloDrew/orgs',
    received_events_url:
      'https://api.github.com/users/BuffaloDrew/received_events',
    repos_url: 'https://api.github.com/users/BuffaloDrew/repos',
    site_admin: false,
    starred_url:
      'https://api.github.com/users/BuffaloDrew/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/BuffaloDrew/subscriptions',
    type: 'User',
    url: 'https://api.github.com/users/BuffaloDrew',
  },
};

module.exports = {
  CLOSED,
  COMMENT_CREATED,
  EDITED,
  LABELED,
  OPENED,
  REOPENED,
  TEST_EXTERNAL_ID,
  UNLABELED,
};
